### ISSUE TITLE
NTR: Zostera (genus)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S25#11]
This new S25 term is needs to support the creation of https://github.com/nvs-vocabs/P01/issues/44

**Comment by gwemon** [comment]
Will be linked to WoRMS record AphiaID: http://www.marinespecies.org/aphia.php?p=taxdetails&id=144233

**Comment by roswri** [comment]
Duplicate ticket created: https://github.com/nvs-vocabs/S25/issues/20

term published to NVS: http://vocab.nerc.ac.uk/collection/S25/current/BE009622/
