### ISSUE TITLE
NTR: Halophila ovalis

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S25#12]
New term needed for the creation of https://github.com/nvs-vocabs/P01/issues/45

**Comment by gwemon** [comment]
Will be linked to WoRMS record and AphiaID: http://www.marinespecies.org/aphia.php?p=taxdetails&id=208930

**Comment by roswri** [comment]
Duplicate ticket created: https://github.com/nvs-vocabs/S25/issues/22

term published to NVS: http://vocab.nerc.ac.uk/collection/S25/current/BE009621/
