### ISSUE TITLE
New S25 terms for various organisms [subcomponent: structural cellular components] for eReefs project (4 terms)

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/S25#26]
S12 required:
https://github.com/nvs-vocabs/S12/issues/24

benthic microalgae [subcomponent: structural cellular components]
phytoplankton [Size: large, subcomponent: structural cellular components]
phytoplankton [Size: small, subcomponent: structural cellular components]
Trichodesmium (ITIS: 918: WoRMS 177604) [subcomponent: structural cellular components]

**Comment by gwemon** [comment]
@roswri I am just wondering if "cell structures" could be expressed as "structural cellular components" to be completely unambiguous about what is being referred to?

**Comment by roswri** [comment]
structural cellular components sounds much better! thanks

**Comment by roswri** [comment]
New terms created:
BE009683 - Trichodesmium (ITIS: 918: WoRMS 177604) [Subcomponent: structural cellular components]
BE009684 - benthic microalgae [Subcomponent: structural cellular components]
BE009682 - phytoplankton [Size: large Subcomponent: structural cellular components]
BE009681 - phytoplankton [Size: small Subcomponent: structural cellular components]

**Comment by roswri** [comment]
Terms published:
http://vocab.nerc.ac.uk/collection/S25/current/BE009681/
http://vocab.nerc.ac.uk/collection/S25/current/BE009682/
http://vocab.nerc.ac.uk/collection/S25/current/BE009683/
http://vocab.nerc.ac.uk/collection/S25/current/BE009684/
