### ISSUE TITLE
New S25 term for  various organisms [subcomponent: intracellular reserve pool]' for eReefs project

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/S25#27]
S12 required:
https://github.com/nvs-vocabs/S12/issues/25

benthic microalgae [subcomponent: intracellular reserve pool]
phytoplankton   [Size: large, subcomponent: intracellular reserve pool]
phytoplankton   [Size: small, subcomponent: intracellular reserve pool]
Trichodesmium   (ITIS: 918: WoRMS 177604) [subcomponent: intracellular reserve pool]

**Comment by gwemon** [comment]
@roswri  can we take time to think about this one. I am not sure "nutrient reserves" is the best option here. What is the link to the eReefs ticket? Do we have one? If not could you remind me what the intended P01 structure is?

**Comment by gwemon** [comment]
I am thinking maybe "intracellular reserves" or even "intracellular reserve pool" might be a better option because you could re-use it for any kind of reserves.

**Comment by roswri** [comment]
@gwemon 
The eReefs ticket is this one: https://github.com/nvs-vocabs/ereefs/issues/17

The P01s will be structured:
Biomass as nitrogen of benthic microalgae (subcomponent: nutrient reserves) per unit volume of the water body by model prediction 

I agree, I think intracellular reserve pool would work, I'll update the S12

**Comment by roswri** [comment]
Terms created:
BE009687 - Trichodesmium (ITIS: 918: WoRMS 177604) [Subcomponent: intracellular reserve pool]
BE009688 - benthic microalgae [Subcomponent: intracellular reserve pool]
BE009686 - phytoplankton [Size: large Subcomponent: intracellular reserve pool]
BE009685 - phytoplankton [Size: small Subcomponent: intracellular reserve pool]

**Comment by roswri** [comment]
Terms published:
http://vocab.nerc.ac.uk/collection/S25/current/BE009685/
http://vocab.nerc.ac.uk/collection/S25/current/BE009686/
http://vocab.nerc.ac.uk/collection/S25/current/BE009687/
http://vocab.nerc.ac.uk/collection/S25/current/BE009688/
