### ISSUE TITLE
NTR: macroalgae

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S25#9]
This new term needs to be added to S25 to support the creation of https://github.com/nvs-vocabs/P01/issues/43
The term "macroalgae" refers to species of multicellular macroscopic algae found in marine or freshwater environments. They include epiphytic species. Marine macroalgae are also known as "seaweeds".

**Comment by roswri** [comment]
Term created:
BE009624 - macroalgae

**Comment by roswri** [comment]
Term now live on the NVS:
http://vocab.nerc.ac.uk/collection/S25/current/BE009624/
